export const FETCH_BOOKS_ERROR = 'FETCH_BOOKS_ERROR'
export const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS'

export const CATEGORY_VALUE = 'CATEGORY_VALUE'
export const SORT_VALUE = 'SORT_VALUE'
export const SEARCH_VALUE = 'SEARCH_VALUE'

export const START_LOADING = 'START_LOADING'